// variables that represent strings that allow me to change my state within my reducer function.

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGN_UP = 'SIGN_UP';

export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const CREATE_LOCATION = 'CREATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const CREATE_VOLUNTEER = 'CREATE_VOLUNTEER';
export const DELETE_VOLUNTEER = 'DELETE_VOLUNTEER';
export const UPDATE_VOLUNTEER = 'UPDATE_VOLUNTEER';

export const CREATE_RESTAURANTS = 'CREATE_RESTAURANTS';
export const DELETE_RESTAURANTS = 'DELETE_RESTAURANTS';
export const UPDATE_RESTAURANTS = 'DELETE_RESTAURANTS';

export const CREATE_REQUEST_PICKUP = 'CREATE_REQUEST_PICKUP';
export const DELETE_REQUEST_PICKUP = 'DELETE_REQUEST_PICKUP';
export const UPDATE_REQUEST_PICKUP = 'UPDATE_REQUEST_PICKUP';
export const FILTER_BUSINESSES = 'FILTER_BUSINESSES';
export const NOTIFY_VOLUNTEER = 'NOTIFY_VOLUNTEER';

export const CREATE_NONPROFITS = 'CREATE_NONPROFITS';
export const DELETE_NONPROFITS = 'DELETE_NONPROFITS';
export const UPDATE_NONPROFITS = 'UPDATE_NONPROFITS';
